{
  "error_id": "error_20250507_021611",
  "timestamp": "2025-05-07T02:16:11.374810",
  "error_message": "list index out of range",
  "traceback": "Traceback (most recent call last):\n  File \"/data/data/com.termux/files/usr/lib/python3.12/site-packages/telegram/ext/_application.py\", line 1298, in process_update\n    await coroutine\n  File \"/data/data/com.termux/files/usr/lib/python3.12/site-packages/telegram/ext/_handlers/basehandler.py\", line 158, in handle_update\n    return await self.callback(update, context)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/storage/emulated/0/documents/Price-Alert-Bot/main_folder/commands.py\", line 681, in launch\n    timestamps = [entry[2].get(\"timestamp\") for entry in history.TOKEN_DATA_HISTORY.values() if entry]\n                  ~~~~~^^^\nIndexError: list index out of range\n",
  "update": {
    "message": {
      "channel_chat_created": false,
      "delete_chat_photo": false,
      "entities": [
        {
          "length": 3,
          "offset": 0,
          "type": "bot_command"
        }
      ],
      "group_chat_created": false,
      "supergroup_chat_created": false,
      "text": "/lc",
      "chat": {
        "first_name": "Adebayo",
        "id": 965551493,
        "last_name": "Toheeb | WEB DEV | WEB DESIGNERüêæ",
        "type": "private",
        "username": "toheeb6538"
      },
      "date": 1746580571,
      "message_id": 2227,
      "from": {
        "first_name": "Adebayo",
        "id": 965551493,
        "is_bot": false,
        "language_code": "en",
        "last_name": "Toheeb | WEB DEV | WEB DESIGNERüêæ",
        "username": "toheeb6538"
      }
    },
    "update_id": 942966982
  }
}